# Generated by Django 5.0.3 on 2024-04-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='festivals',
            field=models.ManyToManyField(related_name='mods', to='api.festival'),
        ),
    ]
