# Generated by Django 5.0.3 on 2024-05-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_festivals'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_festivals',
            field=models.ManyToManyField(related_name='favorite_by', to='api.festival'),
        ),
    ]
