# Generated by Django 5.0.3 on 2024-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_favorite_festivals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_festivals',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favourite_festivals',
            field=models.ManyToManyField(related_name='favourite_by', to='api.festival'),
        ),
    ]
