# Generated by Django 5.0.3 on 2024-07-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_message_options_comment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='img',
            field=models.CharField(null=True),
        ),
    ]
