# Generated by Django 5.0.3 on 2024-07-20 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_festival_date_end_festival_date_start_festival_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='notified_users',
            field=models.ManyToManyField(related_name='chat_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
