# Generated by Django 5.0.3 on 2024-08-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='img',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
