# Generated by Django 5.0.3 on 2024-08-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_message_img_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='img',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
