# Generated by Django 5.0.3 on 2024-08-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_message_img_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
